version: "3.8"

services:
  # app:
  #   image: node:12-alpine
  #   command: sh -c "yarn install && yarn run dev"
  #   ports:
  #     - 3000:3000
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: secret
  #     MYSQL_DB: todos

  app_db:
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - app_db:/var/lib/mysql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app_db_client:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - app_db_client_config:/var/lib/pgadmin
    ports:
      - '80:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=pgadmin

volumes:
  app_db:
  app_db_client_config:
